/**
 * ============================================================================
 * PLATFORM ADMINS — `/api/platform/admins`
 * ============================================================================
 * The tenant list behind Super Admin's "Admin Management" screen.
 *
 * On this backend a **tenant and its admin login are one record, created
 * together in a single call**: `name` labels the company, `admin_email` is the
 * login. That is why one object carries both `companyId`/`name` and
 * `adminUserId`/`email` — they are two halves of the same thing.
 *
 * | Call                                    | What it does                        |
 * |-----------------------------------------|-------------------------------------|
 * | `GET    /platform/admins`               | list, newest first                  |
 * | `POST   /platform/admins`               | create — returns a one-time password |
 * | `GET    /platform/admins/:id`           | read one                            |
 * | `PATCH  /platform/admins/:id`           | rename / change support email only  |
 * | `POST   /platform/admins/:id/disable`   | revoke the admin's access           |
 * | `POST   /platform/admins/:id/enable`    | restore it                          |
 * | `POST   /platform/admins/:id/reset-password` | set a new password             |
 *
 * Two constraints the UI has to respect, because the API defines them:
 *
 *  - **There is no delete.** Tenants are disabled, never removed.
 *  - **`PATCH` accepts only `name` and `support_email`.** The admin's email,
 *    full name and phone are fixed after creation; changing those would mean a
 *    new endpoint.
 *
 * Every call needs the Super Admin's bearer token. React Query hooks that wrap
 * these live in `./use-platform-admins`.
 */

import { currentAccessToken } from "@/services/auth-service"
import { apiFetch, type RequestOptions } from "@/services/http-client"

/* ========================================================================== */
/*  Types                                                                     */
/* ========================================================================== */

/**
 * One tenant plus its admin login. The backend already sends camelCase, so
 * this is the wire shape as-is — only the timestamps are normalised (see
 * `normalise` below).
 */
export interface PlatformAdmin {
  /** Same value as `companyId` — the tenant *is* the admin record. */
  adminId: string
  companyId: string
  /** Company / tenant name. */
  name: string
  /** URL-safe form of `name`, generated by the server at creation. */
  slug: string
  supportEmail: string
  isActive: boolean
  tenancyEnforced: boolean
  /** How many HR seats this tenant has. */
  hrCount: number

  /* The admin login that was created alongside the tenant. */
  adminUserId: string
  email: string
  fullName: string
  mustChangePassword: boolean
  lastLogin: string | null

  createdBy: string
  createdAt: string
  updatedAt: string
}

/** Body of `POST /platform/admins`. */
export interface CreatePlatformAdminInput {
  /** Company name. Required. */
  name: string
  /** The admin's login address. Required, and must not already be a user. */
  adminEmail: string
  adminFullName?: string
  /** E.164, e.g. `+916305865365`. */
  adminPhone?: string
  supportEmail?: string
  /**
   * Optional. Omit and the server derives it from `name`
   * ("Northwind Labs" → "northwind-labs").
   */
  slug?: string
}

/** What comes back from a create — including the only sighting of the password. */
export interface CreatePlatformAdminResult {
  admin: PlatformAdmin
  /**
   * Shown once and never retrievable again: the server does not store it in
   * plaintext. Surface it to the operator before this object is discarded.
   */
  temporaryPassword: string
  /** Whether the server also emailed the credentials. */
  credentialsEmailSent: boolean
  /**
   * False when the follow-up call that switches on data isolation failed. The
   * tenant works, but can see other tenants' interviews until it is retried.
   */
  tenancyEnforced: boolean
  message: string
}

/** Body of `PATCH /platform/admins/:id`. Both fields optional. */
export interface UpdatePlatformAdminInput {
  name?: string
  supportEmail?: string
}

export interface ResetPasswordResult {
  /** Echoed back so the caller can show what was set. */
  newPassword: string
  credentialsEmailSent: boolean
  message: string
}

export interface ListPlatformAdminsOptions {
  /** Omit for every tenant; `true`/`false` to filter by enabled state. */
  isActive?: boolean
  limit?: number
}

/* ========================================================================== */
/*  Wire format                                                               */
/* ========================================================================== */

/** Envelopes the server wraps its payloads in. */
interface AdminEnvelope {
  status: string
  admin: PlatformAdmin
}
interface ListEnvelope {
  status: string
  count: number
  admins: PlatformAdmin[]
}
interface CreateEnvelope extends AdminEnvelope {
  temporaryPassword: string
  credentialsEmailSent: boolean
  message: string
}
interface ResetEnvelope {
  status: string
  credentialsEmailSent: boolean
  message: string
}

/** Every platform endpoint is authenticated, so bake the token in once. */
function authed<T>(path: string, options: Omit<RequestOptions, "token"> = {}) {
  return apiFetch<T>(path, { ...options, token: currentAccessToken() })
}

/**
 * The API sends timestamps with no timezone (`"2026-07-31T14:09:05.836458"`).
 * `new Date()` reads those as **local** time, so a viewer in IST would see
 * every "created" time shifted by 5½ hours. Server time is UTC — say so.
 */
function toUtcIso(value: string): string {
  return /(?:Z|[+-]\d{2}:?\d{2})$/.test(value) ? value : `${value}Z`
}

/** Same, for the nullable `lastLogin`. */
function toUtcIsoOrNull(value: string | null): string | null {
  return value === null ? null : toUtcIso(value)
}

/** Applied to every admin coming out of the API, from any endpoint. */
function normalise(admin: PlatformAdmin): PlatformAdmin {
  return {
    ...admin,
    createdAt: toUtcIso(admin.createdAt),
    updatedAt: toUtcIso(admin.updatedAt),
    lastLogin: toUtcIsoOrNull(admin.lastLogin),
  }
}

/* ========================================================================== */
/*  Calls                                                                     */
/* ========================================================================== */

export async function listPlatformAdmins({
  isActive,
  limit,
}: ListPlatformAdminsOptions = {}): Promise<PlatformAdmin[]> {
  const query = new URLSearchParams()
  if (isActive !== undefined) query.set("is_active", String(isActive))
  if (limit !== undefined) query.set("limit", String(limit))

  const suffix = query.size > 0 ? `?${query}` : ""
  const response = await authed<ListEnvelope>(`/platform/admins${suffix}`)
  return response.admins.map(normalise)
}

export async function getPlatformAdmin(
  adminId: string
): Promise<PlatformAdmin> {
  const response = await authed<AdminEnvelope>(`/platform/admins/${adminId}`)
  return normalise(response.admin)
}

/**
 * Turns data isolation on or off for a tenant.
 *
 * ⚠️ **Tenants are created with this OFF, and that leaks data.** A brand-new
 * admin with `tenancyEnforced: false` sees *every other tenant's* interviews in
 * `GET /api/interviews` — measured: 6 rows across all tenants before the flip,
 * 1 (their own) after. `createPlatformAdmin` therefore enables it immediately;
 * this function exists for repairing tenants created before that was wired.
 */
export async function setTenancyEnforcement(
  adminId: string,
  enforced: boolean
): Promise<PlatformAdmin> {
  const response = await authed<AdminEnvelope>(
    `/platform/admins/${adminId}/tenancy`,
    { method: "POST", body: { enforced } }
  )
  return normalise(response.admin)
}

/**
 * Creates the tenant and its admin login in one shot, and mails the admin their
 * credentials. The returned `temporaryPassword` is the only copy that will ever
 * exist — show it to the operator immediately.
 *
 * Data isolation is switched on straight afterwards, because the create
 * endpoint leaves it off (see `setTenancyEnforcement`). If that second call
 * fails the tenant still exists and is usable, so the result reports
 * `tenancyEnforced: false` rather than throwing — the caller warns instead of
 * pretending the whole create failed.
 */
export async function createPlatformAdmin(
  input: CreatePlatformAdminInput
): Promise<CreatePlatformAdminResult> {
  const response = await authed<CreateEnvelope>("/platform/admins", {
    method: "POST",
    body: {
      name: input.name.trim(),
      admin_email: input.adminEmail.trim().toLowerCase(),
      admin_full_name: input.adminFullName?.trim() ?? "",
      admin_phone: input.adminPhone?.trim() ?? "",
      support_email: input.supportEmail?.trim() ?? "",
      // Only send a slug when the caller chose one; otherwise let the server
      // derive it from the name.
      ...(input.slug?.trim() ? { slug: input.slug.trim() } : {}),
    },
  })

  let admin = normalise(response.admin)
  let tenancyEnforced = admin.tenancyEnforced

  if (!tenancyEnforced) {
    try {
      admin = await setTenancyEnforcement(admin.adminId, true)
      tenancyEnforced = admin.tenancyEnforced
    } catch {
      // Left for the caller to surface — the tenant is created either way.
      tenancyEnforced = false
    }
  }

  return {
    admin,
    tenancyEnforced,
    temporaryPassword: response.temporaryPassword,
    credentialsEmailSent: response.credentialsEmailSent,
    message: response.message,
  }
}

/**
 * Renames a tenant or changes its support address.
 *
 * Note the server does **not** regenerate `slug` on rename — the original stays
 * put, which keeps any URL built from it working.
 */
export async function updatePlatformAdmin(
  adminId: string,
  input: UpdatePlatformAdminInput
): Promise<PlatformAdmin> {
  const body: Record<string, string> = {}
  if (input.name !== undefined) body.name = input.name.trim()
  if (input.supportEmail !== undefined) {
    body.support_email = input.supportEmail.trim()
  }

  const response = await authed<AdminEnvelope>(`/platform/admins/${adminId}`, {
    method: "PATCH",
    body,
  })
  return normalise(response.admin)
}

/** Revokes or restores the admin's access. There is no delete on this API. */
export async function setPlatformAdminActive(
  adminId: string,
  isActive: boolean
): Promise<PlatformAdmin> {
  const response = await authed<AdminEnvelope>(
    `/platform/admins/${adminId}/${isActive ? "enable" : "disable"}`,
    { method: "POST" }
  )
  return normalise(response.admin)
}

/**
 * Sets a new password for the admin and forces a change at next sign-in.
 *
 * The endpoint requires the caller to *supply* the password — it does not mint
 * one — so `generateTemporaryPassword()` is the default rather than asking a
 * human to invent a throwaway.
 */
export async function resetPlatformAdminPassword(
  adminId: string,
  newPassword: string = generateTemporaryPassword()
): Promise<ResetPasswordResult> {
  const response = await authed<ResetEnvelope>(
    `/platform/admins/${adminId}/reset-password`,
    {
      method: "POST",
      body: { new_password: newPassword, must_change_password: true },
    }
  )

  return {
    newPassword,
    credentialsEmailSent: response.credentialsEmailSent,
    message: response.message,
  }
}

/* ========================================================================== */
/*  Helpers                                                                   */
/* ========================================================================== */

const PASSWORD_GROUPS = [
  "ABCDEFGHJKLMNPQRSTUVWXYZ", // no I/O — easy to misread when read aloud
  "abcdefghijkmnopqrstuvwxyz", // no l
  "23456789", // no 0/1
  "!@#$%&*?",
] as const

/**
 * A 16-character throwaway password with at least one character from each
 * group, using `crypto.getRandomValues` rather than `Math.random` — this value
 * is a live credential until the admin changes it.
 */
export function generateTemporaryPassword(length = 16): string {
  const alphabet = PASSWORD_GROUPS.join("")

  // Start with one guaranteed character per group so the result always
  // satisfies a mixed-character policy, then fill the rest freely.
  const picks = [
    ...PASSWORD_GROUPS.map(pickFrom),
    ...Array.from({ length: Math.max(0, length - PASSWORD_GROUPS.length) }, () =>
      pickFrom(alphabet)
    ),
  ]

  return shuffle(picks).join("")
}

function randomInts(count: number): Uint32Array {
  return crypto.getRandomValues(new Uint32Array(count))
}

function pickFrom(characters: string): string {
  return characters[randomInts(1)[0] % characters.length]
}

/** Fisher-Yates, so the guaranteed characters aren't always at the front. */
function shuffle(items: string[]): string[] {
  const result = [...items]
  const random = randomInts(result.length)

  for (let i = result.length - 1; i > 0; i -= 1) {
    const j = random[i] % (i + 1)
    ;[result[i], result[j]] = [result[j], result[i]]
  }
  return result
}
